import type { ScanResult } from '../../types/index.js';
import { formatBytes } from '../../utils/bytes.js';

export function generateMarkdownReport(result: ScanResult): string {
  const lines: string[] = [];

  lines.push('# imgclean Image Health Report\n');
  lines.push(`- **Scanned Directory:** \`${result.rootPath}\``);
  lines.push(`- **Total Images:** ${result.totalImages}`);
  lines.push(`- **Total Image Size:** ${formatBytes(result.totalSize)}`);
  if (result.potentialSavings > 0) {
    lines.push(`- **Potential Savings:** **${formatBytes(result.potentialSavings)}**`);
  }
  lines.push(`- **Scan Duration:** ${result.scanDurationMs}ms\n`);

  // 1. Budget Summary (if available)
  if (result.budget) {
    lines.push('## Image Budget');
    lines.push('| Metric | Value | Status |');
    lines.push('| :--- | :--- | :--- |');
    const totalBudgetStr = result.budget.totalBudget ? formatBytes(result.budget.totalBudget) : 'N/A';
    lines.push(`| Total Budget | ${formatBytes(result.totalSize)} / ${totalBudgetStr} | ${result.budget.passedTotal ? '✅ Passed' : '❌ Exceeded'} |`);
    if (result.budget.singleBudget) {
      lines.push(`| Single File Budget | Max ${formatBytes(result.budget.singleBudget)} | ${result.budget.passedSingle ? '✅ Passed' : '❌ Exceeded'} |`);
    }
    lines.push('');
  }

  // 2. Format Breakdown
  const formatEntries = Object.entries(result.formatBreakdown);
  if (formatEntries.length > 0) {
    lines.push('## Format Breakdown');
    lines.push('| Format | File Count | Total Size | % of Total |');
    lines.push('| :--- | :--- | :--- | :--- |');
    for (const [fmt, stat] of formatEntries) {
      const pct = result.totalSize > 0 ? ((stat.size / result.totalSize) * 100).toFixed(1) : '0.0';
      lines.push(`| **${fmt}** | ${stat.count} | ${formatBytes(stat.size)} | ${pct}% |`);
    }
    lines.push('');
  }

  // 3. Issues Summary
  if (result.issues.length > 0) {
    lines.push('## Detected Issues');
    lines.push('| File | Type | Severity | Message | Potential Savings |');
    lines.push('| :--- | :--- | :--- | :--- | :--- |');
    for (const issue of result.issues) {
      const savings = issue.potentialSavings ? formatBytes(issue.potentialSavings) : '-';
      lines.push(`| \`${issue.file}\` | \`${issue.type}\` | ${issue.severity} | ${issue.message} | ${savings} |`);
    }
    lines.push('');
  }

  // 4. Exact Duplicates
  if (result.duplicates.length > 0) {
    lines.push('## Exact Duplicates (SHA-256)');
    for (const group of result.duplicates) {
      lines.push(`- **Potential Savings:** ${formatBytes(group.potentialSavings)} (${group.files.length} copies)`);
      for (const f of group.files) {
        lines.push(`  - \`${f}\``);
      }
    }
    lines.push('');
  }

  // 5. Possibly Unused Images
  if (result.possiblyUnused.length > 0) {
    lines.push('## Possibly Unused Images');
    lines.push('> ℹ️ *These images were not found in static code references. Verify before removing.*');
    for (const unused of result.possiblyUnused) {
      lines.push(`- \`${unused}\``);
    }
    lines.push('');
  }

  // 6. Largest Files (Top 10)
  if (result.images.length > 0) {
    const sorted = [...result.images].sort((a, b) => b.size - a.size).slice(0, 10);
    lines.push('## Largest Images');
    lines.push('| File | Format | Dimensions | Size |');
    lines.push('| :--- | :--- | :--- | :--- |');
    for (const img of sorted) {
      const dims = img.width && img.height ? `${img.width}×${img.height}` : '-';
      lines.push(`| \`${img.path}\` | ${img.format.toUpperCase()} | ${dims} | ${formatBytes(img.size)} |`);
    }
    lines.push('');
  }

  lines.push('---\n*Generated by [imgclean](https://github.com/rajank18/imgclean)*');

  return lines.join('\n');
}
